# Site settings
title: BennieMosher.com
markdown: kramdown
highlighter: pygments
url: "http://benniemosher.com" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

collections:
  jobs:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: :compressed

jekyll_timeago:
  depth: 1
