# Site settings
title: Bennie Mosher
email: benniemosher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Architect in Windsor, Colorado. Specializing in Ruby on Rails,
  Javascript, HTML, CSS and solving companies largest problems with easy maintanable solutions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benniemosher.com" # the base hostname & protocol for your site
twitter_username: benniemosher
github_username:  benniemosher

# Build settings
markdown: kramdown
