# Site settings
title: BennieMosher.com
markdown: kramdown
highlighter: pygments
url: "http://benniemosher.com" # the base hostname & protocol for your site
twitter_username: benniemosher
github_username:  benniemosher

collections:
  jobs:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: :compressed

jekyll_timeago:
  depth: 1
