# Site settings
title: BAMosher.com
markdown: kramdown
highlighter: pygments
url: "http://bamosher.com" # the base hostname & protocol for your site

collections:
  jobs:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: :compressed

jekyll_timeago:
  depth: 1
