# Site settings
timezone: "America/Los Angeles"
title: BAMosher.com
email: ben@bamosher.com
markdown: kramdown
highlighter: pygments
url: "https://bamosher.com" # the base hostname & protocol for your site
collections:
  jobs:
    output: false
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-timeago
sass:
  sass_dir: _sass
  style: :compressed
jekyll_timeago:
  depth: 1
